### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Kurogoma4D** [cb-cloud/flutter_in_app_notification#1]
- [x] Add dart analyzer rule
- [x] Add doc comments
- [x] Organize example
- [x] v0.1.0 release
- [x] Migrate null-safety
  - [x] v0.2.0 release
